# Generated by Django 2.0 on 2019-05-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto_roulette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_category', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
